dashboards:
- name: jetstack-cert-manager-master
  dashboard_tab:
  - base_options: width=10
    code_search_path: https://github.com/jetstack/cert-manager/search
    code_search_url_template:
      url: https://github.com/jetstack/cert-manager/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: title
        value: 'Bazel: <test-name>'
      - key: body
        value: <test-url>
      url: https://github.com/jetstack/cert-manager/issues/new
    name: cert-manager-master-bazel
    description: Bazel verify results
    open_bug_template:
      url: https://github.com/jetstack/cert-manager/issues/
    open_test_template:
      url: https://prow.build-infra.jetstack.net/view/gcs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.build-infra.jetstack.net/job-history/<gcs_prefix>
    test_group_name: ci-cert-manager-bazel
  - base_options: width=10
    code_search_path: https://github.com/jetstack/cert-manager/search
    code_search_url_template:
      url: https://github.com/jetstack/cert-manager/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: title
        value: 'Bazel (experimental): <test-name>'
      - key: body
        value: <test-url>
      url: https://github.com/jetstack/cert-manager/issues/new
    name: cert-manager-master-bazel-experimental
    description: Bazel verify results using newest/unreleased Bazel version
    open_bug_template:
      url: https://github.com/jetstack/cert-manager/issues/
    open_test_template:
      url: https://prow.build-infra.jetstack.net/view/gcs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.build-infra.jetstack.net/job-history/<gcs_prefix>
    test_group_name: ci-cert-manager-bazel-experimental
  - base_options: width=10
    code_search_path: https://github.com/jetstack/cert-manager/search
    code_search_url_template:
      url: https://github.com/jetstack/cert-manager/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: title
        value: 'E2E: <test-name>'
      - key: body
        value: <test-url>
      url: https://github.com/jetstack/cert-manager/issues/new
    name: cert-manager-master-e2e-v1-11
    description: End-to-end tests using Kubernetes 1.11
    open_bug_template:
      url: https://github.com/jetstack/cert-manager/issues/
    open_test_template:
      url: https://prow.build-infra.jetstack.net/view/gcs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.build-infra.jetstack.net/job-history/<gcs_prefix>
    test_group_name: ci-cert-manager-e2e-v1-11
  - base_options: width=10
    code_search_path: https://github.com/jetstack/cert-manager/search
    code_search_url_template:
      url: https://github.com/jetstack/cert-manager/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: title
        value: 'E2E: <test-name>'
      - key: body
        value: <test-url>
      url: https://github.com/jetstack/cert-manager/issues/new
    name: cert-manager-master-e2e-v1-12
    description: End-to-end tests using Kubernetes 1.12
    open_bug_template:
      url: https://github.com/jetstack/cert-manager/issues/
    open_test_template:
      url: https://prow.build-infra.jetstack.net/view/gcs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.build-infra.jetstack.net/job-history/<gcs_prefix>
    test_group_name: ci-cert-manager-e2e-v1-12
  - base_options: width=10
    code_search_path: https://github.com/jetstack/cert-manager/search
    code_search_url_template:
      url: https://github.com/jetstack/cert-manager/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: title
        value: 'E2E: <test-name>'
      - key: body
        value: <test-url>
      url: https://github.com/jetstack/cert-manager/issues/new
    name: cert-manager-master-e2e-v1-13
    description: End-to-end tests using Kubernetes 1.13
    open_bug_template:
      url: https://github.com/jetstack/cert-manager/issues/
    open_test_template:
      url: https://prow.build-infra.jetstack.net/view/gcs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.build-infra.jetstack.net/job-history/<gcs_prefix>
    test_group_name: ci-cert-manager-e2e-v1-13
  - base_options: width=10
    code_search_path: https://github.com/jetstack/cert-manager/search
    code_search_url_template:
      url: https://github.com/jetstack/cert-manager/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: title
        value: 'E2E: <test-name>'
      - key: body
        value: <test-url>
      url: https://github.com/jetstack/cert-manager/issues/new
    name: cert-manager-master-e2e-v1-14
    description: End-to-end tests using Kubernetes 1.14
    open_bug_template:
      url: https://github.com/jetstack/cert-manager/issues/
    open_test_template:
      url: https://prow.build-infra.jetstack.net/view/gcs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.build-infra.jetstack.net/job-history/<gcs_prefix>
    test_group_name: ci-cert-manager-e2e-v1-14
  - base_options: width=10
    code_search_path: https://github.com/jetstack/cert-manager/search
    code_search_url_template:
      url: https://github.com/jetstack/cert-manager/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: title
        value: 'E2E: <test-name>'
      - key: body
        value: <test-url>
      url: https://github.com/jetstack/cert-manager/issues/new
    name: cert-manager-master-e2e-v1-15
    description: End-to-end tests using Kubernetes 1.15
    open_bug_template:
      url: https://github.com/jetstack/cert-manager/issues/
    open_test_template:
      url: https://prow.build-infra.jetstack.net/view/gcs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.build-infra.jetstack.net/job-history/<gcs_prefix>
    test_group_name: ci-cert-manager-e2e-v1-15
  - base_options: width=10
    code_search_path: https://github.com/jetstack/cert-manager/search
    code_search_url_template:
      url: https://github.com/jetstack/cert-manager/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: title
        value: 'E2E: <test-name>'
      - key: body
        value: <test-url>
      url: https://github.com/jetstack/cert-manager/issues/new
    name: cert-manager-master-e2e-v1-16
    description: End-to-end tests using Kubernetes 1.16
    open_bug_template:
      url: https://github.com/jetstack/cert-manager/issues/
    open_test_template:
      url: https://prow.build-infra.jetstack.net/view/gcs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.build-infra.jetstack.net/job-history/<gcs_prefix>
    test_group_name: ci-cert-manager-e2e-v1-16
  - base_options: width=10
    code_search_path: https://github.com/jetstack/cert-manager/search
    code_search_url_template:
      url: https://github.com/jetstack/cert-manager/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: title
        value: 'E2E: <test-name>'
      - key: body
        value: <test-url>
      url: https://github.com/jetstack/cert-manager/issues/new
    name: cert-manager-master-e2e-v1-17
    description: End-to-end tests using Kubernetes 1.17
    open_bug_template:
      url: https://github.com/jetstack/cert-manager/issues/
    open_test_template:
      url: https://prow.build-infra.jetstack.net/view/gcs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.build-infra.jetstack.net/job-history/<gcs_prefix>
    test_group_name: ci-cert-manager-e2e-v1-17

# These are periodic jobs that target the master branch of cert-manager
test_groups:
- gcs_prefix: jetstack-logs/logs/ci-cert-manager-bazel
  name: ci-cert-manager-bazel
- gcs_prefix: jetstack-logs/logs/ci-cert-manager-bazel-experimental
  name: ci-cert-manager-bazel-experimental
- gcs_prefix: jetstack-logs/logs/ci-cert-manager-e2e-v1-11
  name: ci-cert-manager-e2e-v1-11
- gcs_prefix: jetstack-logs/logs/ci-cert-manager-e2e-v1-12
  name: ci-cert-manager-e2e-v1-12
- gcs_prefix: jetstack-logs/logs/ci-cert-manager-e2e-v1-13
  name: ci-cert-manager-e2e-v1-13
- gcs_prefix: jetstack-logs/logs/ci-cert-manager-e2e-v1-14
  name: ci-cert-manager-e2e-v1-14
- gcs_prefix: jetstack-logs/logs/ci-cert-manager-e2e-v1-15
  name: ci-cert-manager-e2e-v1-15
- gcs_prefix: jetstack-logs/logs/ci-cert-manager-e2e-v1-16
  name: ci-cert-manager-e2e-v1-16
- gcs_prefix: jetstack-logs/logs/ci-cert-manager-e2e-v1-17
  name: ci-cert-manager-e2e-v1-17
